### ISSUE TITLE
at-someone-online pings users without roles or no longer on the server. 

### ISSUE THREAD

**Issue by findtravishere** [Yes-Theory-Fam/yesbot-ts#126]
noticed this while people are using the command and users without roles are being pinged. 

users don't seem to be on the server as well. seems like the same issue with at-group that hakon brought up.

**Comment by geisterfurz007** [comment]
Hm, it shouldn't be because that is not stuff stored in the database. In fact the bot looks at all members of the role and selects a random one so the information *should* be up to date. Only things that come to mind are either a Discord API hiccup or an expired cache of the bot.

How frequently does this happen?

**Comment by findtravishere** [comment]
Wasn't around the server much recently, but I noticed it once today. Discord API has been slow to fetch user roles as well but it's been about 5 hours and this user's roles still aren't up. Looked up the user, user is no longer in the server. 

Maybe the user was here before and is still stored in the database? 

![image](https://user-images.githubusercontent.com/63047970/92304745-5572e900-efb3-11ea-9c7b-1ea76b2ab5d2.png)

**Comment by geisterfurz007** [comment]
The someone command does not use the database at all so that cannot be it (the relevant code is [here](https://github.com/Yes-Theory-Fam/yesbot-ts/blob/master/src/programs/Someone.ts#L103)). The only way I see this could have happened is either the user leaving very shortly after the ping (which can happen if users get reminded of a server they don't want to be one anymore) or the user still being in `sdRole.members` still containing the user despite them having left before because the cache was not updated (which can happen as discord.js doesn't update all caches on every event for performance).

**Comment by findtravishere** [comment]
Ok! Thanks for checking, 😄  seems like an issue on discordjs' side. Closing the issue.
