### ISSUE TITLE
Deploy the bot as Docker Application

### ISSUE THREAD

**Issue by adrian-goe** [Yes-Theory-Fam/yesbot-ts#255]
Auto deploy the bot with GitHub action.
* on master as preview instance
* on tag as production instance

**Comment by adrian-goe** [comment]
this issue is blocked by #254

**Comment by sklirg** [comment]
Not sure if this fits exactly into this issue, but anyways:

Update github actions with different steps and allow them to run on PRs/pushes.

Examples:
- linting, should not require installing a private npm package - can be run on PR
- (unit) testing, should not require installing a private npm package - can be run on PR
- (integration) testing (prisma), depends on installing a private npm package - should not be run on PR (since this can expose the github secret used in installing the package)

**Comment by adrian-goe** [comment]
Partially done with:

- https://github.com/Yes-Theory-Fam/yesbot-ts/pull/330
- https://github.com/Yes-Theory-Fam/yesbot-ts/pull/343
- https://github.com/Yes-Theory-Fam/yesbot-ts/pull/344
- https://github.com/Yes-Theory-Fam/yesbot-ts/pull/345

**Comment by adrian-goe** [comment]
Need to add the deployment script
