### ISSUE TITLE
Poll emojis are not ordered in the way they were sent in the message

### ISSUE THREAD

**Issue by geisterfurz007** [Yes-Theory-Fam/yesbot-ts#296]
In the screenshot below, the emojis should have been ordered incrementally, instead they are seemingly randomized:

![grafik](https://user-images.githubusercontent.com/26303198/123131952-7c20e400-d44e-11eb-99d9-74e2119a5cf1.png)

**Comment by hasanlatch007** [comment]
I tried replicating this multiple times (F to my ctrl+v buttons), the emojis are always in order, I thought maybe if it's 2 messages sent at the same time, but again it works fine, maybe if I try this with 2 different accounts I would get a different outcome. Plus when this poll was posted, he was the only one posting so this must be replicable by 1 user, he posted the 2 messages with one minute difference which is pretty damn quick but possible since all he does is just add the numbers and press return, (He is a phone user). I checked discord API response time around his post and saw it was quite high and bouncing all over the place, it was around 122 ms when he posted his poll, so could it simply be that reason?
The next poll posted by another user was also posted around the same time the API response time was suffering, but I guess 2 reaction emojis are easier to add than 10.
Again I have no idea what I am doing or even testing this right 🤔

**Comment by hasanlatch007** [comment]
Here is a screenshot of the API response time around the time he posted his poll.

![Screenshot (760)](https://user-images.githubusercontent.com/6049462/123148093-1e959300-d460-11eb-93e9-b8f49137e1e3.png)

**Comment by adrian-goe** [comment]
that sounds plausible. Since each of these reactions is in its own request it can come to racing conditions.
You could check if the previous reaction is there and then set the next one.
Instead of await message.react(reaction.emoji) we do recursive thing like this
```
function addReactions(reactionList, message){
  const x= reactionList.shift();
  message.react(x).then(()=>{
    if(!!reatcionList.length){
      addReactions(reactionList, message))
    }
  })
}
```
Then we would send each reaction after the one before was successfully sent. That would increase the time until all reactions are set, but would keep the order.
Keep in mind, that juts pseudo code.

**Comment by geisterfurz007** [comment]
That depends on the assumption that the promise is resolved when the reaction is guaranteed to show up. If I am not mistaken, the current code does the same in a much more readable fashion:

https://github.com/Yes-Theory-Fam/yesbot-ts/blob/d9515ba8ca847620ea204e3f22ad5074ea70aa6c/src/programs/polls.ts#L101-L103

From my understanding the underlying assumption is apparently wrong but I don't see a way we can sensibly test that. I am fairly certain that when the promise resolves, the reaction is added to the message in the client's cache so we would have to use an independent, second client to listen for reactions adds. I am not sure that effort is warranted.

**Comment by hasanlatch007** [comment]
If I were to stress test my wifi while hosting the test bot that should lag it enough to replicate the issue if it was a cause of the API high ping or would it just extra slowly add the reactions?

**Comment by geisterfurz007** [comment]
Haven't seen complaints on this for quite a long time. Closing.
