### ISSUE TITLE
Create !help command

### ISSUE THREAD

**Issue by hasanlatch007** [Yes-Theory-Fam/yesbot-ts#333]
Since the influx of new members, maybe adding a `!help` command to use the bot especially in #bot-commands won't be that bad of an idea.

More ideas: 
- Depending on which chat `!help` was used example if in #chat it could return `!deadchat` and more, if in #bot-commands the voice and group commands
- Maybe the ability to edit the description without having to change it in the code directly could put in the DB and modify it there (no clue if this is possible need to update my docker and prisma skills :')🤔

**Comment by geisterfurz007** [comment]
The !help command makes a lot more sense to add when we have the new event system in place for all message based interactions with the bot. Since all commands are registered with a trigger, channels in which they are valid, the role needed to use (if any) and a description, we can generate channel and even role specific help messages from the data that we collect for the event handling.

**Comment by geisterfurz007** [comment]
Since that is the intended way to implement it, I marked this as blocked until all commands are fully moved over.

**Comment by geisterfurz007** [comment]
Not relevant anymore with Slash Commands finally in place. The bot becomes self-documented at that point with all commands and options having description fields and proper names.
