### ISSUE TITLE
at-group pings people no longer on the server and/or deleted accounts

### ISSUE THREAD

**Issue by sklirg** [Yes-Theory-Fam/yesbot-ts#37]
When people delete their accounts from Discord or leave the server, we do not clean up their information in our separate database. This means that we keep pinging non-existing user accounts. While it is not a problem to do so, it looks weird when people are mentioned and some of the mentions have their names show up and some have `<@!snowflake>`.

Suggestion:
Listen for guild member remove gateway event[0], and do cleanup when that happens. Verify that this is sent for a deleted user as well.

Other suggestions welcome.

0: https://discord.com/developers/docs/topics/gateway#guild-member-remove

**Comment by jamie-legg** [comment]
This is definitely something that requires development. The entire flow around `guildMemberDidLeave` could use revamping to maybe even backup roles, nicknames, groups, and then have them restored once that user ID rejoins. I'll leave this up and create a task in the backlog.

**Comment by geisterfurz007** [comment]
This was addressed by #80 but still needs some cleanup to remove people from the database that are not on the server anymore

**Comment by geisterfurz007** [comment]
The method that removes members from user groups is flawed; here is the code:

https://github.com/Yes-Theory-Fam/yesbot-ts/blob/cb93476495e8a0196d53902ab897858efc4b3602/src/events/MemberLeave.ts#L59-L92

You can see that starting line 67, the groups are iterated under the assumption that they are group names which they are not. Because of that, the `findOne` call in line 68 does not return anything and the user who left is not removed from the group.

## Implementation

This can be fixed by removing lines 68-78 and changing the name of the parameter in the `forEach` function to `groups`. You can also remove the `async` keyword since it's not used anymore.

**Comment by geisterfurz007** [comment]
Closed in 87b1e2cc7edff3414dbac2f74efed2a7a060f448
