### ISSUE TITLE
!voice random picker assigns members without Yes Theory role

### ISSUE THREAD

**Issue by geisterfurz007** [Yes-Theory-Fam/yesbot-ts#393]
The random assignment might assign someone who doesn't have the Yes Theory role so they cannot manipulate the room.

There are two ways of approaching this:
- Narrowing down the list of members who may randomly be picked to only those with the role
- Assigning the role to the randomly picked member

Each comes with its pros and cons; narrowing down the list might leave us with noone which would mean that room must be closed but would avoid more complex logic to cover that edge case; assigning the role poses the same questions as #200.

**Comment by hasanlatch007** [comment]
Why not use both ideas? If it comes to None then we could assign the role?

**Comment by joshtrivedi** [comment]
Check if the person picked for the random assignment has the role, if not, just give it to them, because they were already in a call hence yes theory role condition is satisfied.
- however this may be exploited as a loophole and people would start joining 2 person calls and leave from one to get the role, so ethical hotfix can be checking if the random person has the yes theory role, if not, shuffle again.
- the problem with the above fix would be is the call might have to get dropped if no one with the yes theory role is found.

**Comment by geisterfurz007** [comment]
Yeah, currently the room is just dropped. From what I know, this hasn't happened in the two years since I wrote the OP (at least nobody complained) so don't fix what nobody knows is broken 😄
